CG_PARAMS:
  HESSIAN_REG_FACTOR: 0.9
  INIT_HESSIAN_REG: 0.4
  NUM_CG_ITER: 2
  NUM_NEWTON_ITER: 50
DATALOADER:
  ASPECT_RATIO_GROUPING: false
DATASETS:
  TEST: !!python/tuple
  - coco_test_hda_all
  TRAIN: !!python/tuple
  - coco_trainval_hda_all_5shot
MODEL:
  BACKBONE:
    FREEZE: true
  MASK_ON: false
  PROPOSAL_GENERATOR:
    FREEZE: true
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    FREEZE_FEAT: true
    NAME: HDAROIHeads
    NUM_CLASSES: 80
    NUM_CLASSES_HIER1: 42
    NUM_CLASSES_HIER2_BG: 20
    NUM_CLASSES_HIER2_FG: 60
    NUM_CLASSES_HIER2_FG_ANIMAL: 10
    NUM_CLASSES_HIER2_FG_FOOD: 10
    OUTPUT_LAYER: FastRCNNOutputLayers
  WEIGHTS: checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_all/model_reset_surgery_ts_new_setting_bbox.pth
OUTPUT_DIR: ./checkpoints/thesis/checkpoints_HDA_CG_new_setting/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_fc_all_5shot
SOLVER:
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 50
  IMS_PER_BATCH: 16
  IMS_PER_BATCH_FEAT_EXTRACT: 10
  MAX_ITER: 16000
  STEPS: (14400,)
  WARMUP_ITERS: 10
_BASE_: ../../Base-RCNN-FPN.yaml
