_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_reset_remove.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 20
    OUTPUT_LAYER: "FastRCNNOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  #add
  PRETRAINED_BASE_MODEL: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_final.pth"
DATASETS:
  TRAIN: ('coco_trainval_novel_1shot',)
  TEST: ('coco_test_novel',)
SOLVER:
  IMS_PER_BATCH: 16
  # add
  IMS_PER_BATCH_FEAT_EXTRACT: 10
  BASE_LR: 0.01
  STEPS: (10000,)
  MAX_ITER: 500
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
# add
DATALOADER:
  ASPECT_RATIO_GROUPING: False

OUTPUT_DIR: "checkpoints_TFA_SGD/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_1shot"
