DATALOADER:
  ASPECT_RATIO_GROUPING: false
DATASETS:
  TEST: !!python/tuple
  - coco_test_novel
  TRAIN: !!python/tuple
  - coco_trainval_novel_3shot
MODEL:
  BACKBONE:
    FREEZE: true
  MASK_ON: false
  PRETRAINED_BASE_MODEL: checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_final.pth
  PROPOSAL_GENERATOR:
    FREEZE: true
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    FREEZE_FEAT: true
    NUM_CLASSES: 20
    OUTPUT_LAYER: FastRCNNOutputLayers
  WEIGHTS: checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_reset_remove.pth
OUTPUT_DIR: ./checkpoints_TFA_SGD/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_3shot
SOLVER:
  BASE_LR: 0.01
  CHECKPOINT_PERIOD: 1500
  IMS_PER_BATCH: 16
  IMS_PER_BATCH_FEAT_EXTRACT: 10
  MAX_ITER: 1500
  STEPS: !!python/tuple
  - 10000
  WARMUP_ITERS: 0
_BASE_: ../Base-RCNN-FPN.yaml
