CG_PARAMS:
  HESSIAN_REG_FACTOR: 0.9
  INIT_HESSIAN_REG: 0.4
  NUM_CG_ITER: 2
  NUM_NEWTON_ITER: 30
DATALOADER:
  ASPECT_RATIO_GROUPING: false
DATASETS:
  TEST: !!python/tuple
  - coco_test_all
  TRAIN: !!python/tuple
  - coco_trainval_all_3shot
MODEL:
  BACKBONE:
    FREEZE: true
  MASK_ON: false
  PRETRAINED_BASE_MODEL: checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_final.pth
  PROPOSAL_GENERATOR:
    FREEZE: true
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    FREEZE_FEAT: true
    NAME: TwoStageROIHeads
    NUM_CLASSES: 80
    NUM_CLASSES_BASE: 60
    NUM_CLASSES_NOVEL: 20
    OUTPUT_LAYER: FastRCNNOutputLayers
  WEIGHTS: checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_all/model_reset_surgery_ts.pth
OUTPUT_DIR: ./checkpoints_HDA_CG/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_fc_all_3shot
SOLVER:
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 30
  IMS_PER_BATCH: 16
  IMS_PER_BATCH_FEAT_EXTRACT: 10
  MAX_ITER: 16000
  STEPS: (14400,)
  WARMUP_ITERS: 10
_BASE_: ../Base-RCNN-FPN.yaml
