from detectron2.config import CfgNode as CN
from detectron2.config.defaults import _C

# adding additional default values built on top of the default values in detectron2

_CC = _C

# FREEZE Parameters
_CC.MODEL.BACKBONE.FREEZE = False
_CC.MODEL.PROPOSAL_GENERATOR.FREEZE = False
_CC.MODEL.ROI_HEADS.FREEZE_FEAT = False
_CC.MODEL.ROI_HEADS.CLS_SCORE_LARGE_BIAS = False

# choose from "FastRCNNOutputLayers" and "CosineSimOutputLayers"
_CC.MODEL.ROI_HEADS.OUTPUT_LAYER = "FastRCNNOutputLayers"
# scale of cosine similarity (set to -1 for learnable scale)
_CC.MODEL.ROI_HEADS.COSINE_SCALE = 20.0
# Specify the number of base and novel classes for Hierarchical Detection Approach
_CC.MODEL.ROI_HEADS.NUM_CLASSES_BASE = None 
_CC.MODEL.ROI_HEADS.NUM_CLASSES_NOVEL = None 

# set the path for the pretrained base model weights
_CC.MODEL.PRETRAINED_BASE_MODEL = None

# Backward Compatible options.
_CC.MUTE_HEADER = True

# Set the batch size for feature extraction
_CC.SOLVER.IMS_PER_BATCH_FEAT_EXTRACT = 10

# CG parameters
_CC.CG_PARAMS = CN()
_CC.CG_PARAMS.NUM_NEWTON_ITER_WARMUP = 0
_CC.CG_PARAMS.NUM_NEWTON_ITER = 100
_CC.CG_PARAMS.NUM_CG_ITER = 10
_CC.CG_PARAMS.REGULARIZATION_TYPE = None
_CC.CG_PARAMS.INIT_HESSIAN_REG = 0.0
_CC.CG_PARAMS.HESSIAN_REG_FACTOR = 1.0
_CC.CG_PARAMS.CG_EPS = 0.0
_CC.CG_PARAMS.FLETCHER_REEVES = True
_CC.CG_PARAMS.STANDARD_ALPHA = True
_CC.CG_PARAMS.DIRECTION_FORGET_FACTOR = 0
_CC.CG_PARAMS.DEBUG = False
_CC.CG_PARAMS.ANALYZE_CONVERGENCE = False
_CC.CG_PARAMS.PLOTTING = False
_CC.CG_PARAMS.LOSS_REG = 0.0
_CC.CG_PARAMS.LOSS_VEC_REG_PATH = None
_CC.CG_PARAMS.AUGMENTATION = False
_CC.CG_PARAMS.PRED_INIT_WEIGHT = False
_CC.CG_PARAMS.WEIGHT_PREDICTOR_PATH = None
_CC.CG_PARAMS.FEATURE_PROJECTOR_PATH = None

# Meta learning parameters
_CC.META_PARAMS = CN()
_CC.META_PARAMS.MODEL_WEIGHTS = "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_final.pth"
_CC.META_PARAMS.REGULARIZATION_TYPE = None
_CC.META_PARAMS.INIT_LOSS_REG = 0.005
_CC.META_PARAMS.NUM_ITER = 1000

_CC.META_PARAMS.TASKS_PER_BATCH = 1
_CC.META_PARAMS.SUPPORT_SET_SHOTS = 1
_CC.META_PARAMS.QUERY_SET_SHOTS = 2
_CC.META_PARAMS.BASE_CATEGORIES_PATH = 'datasets/cocosplit/datasplit/coco_base_categories.pt'
_CC.META_PARAMS.TRAINING_DATA_PATH = 'datasets/cocosplit/datasplit/trainvalno5k.json'

_CC.META_PARAMS.OUTER_OPTIM = CN()
_CC.META_PARAMS.OUTER_OPTIM.BASE_LR = 0.001
_CC.META_PARAMS.OUTER_OPTIM.MOMENTUM = 0.9
_CC.META_PARAMS.OUTER_OPTIM.NESTEROV = False
_CC.META_PARAMS.OUTER_OPTIM.WEIGHT_DECAY = 0.0001

_CC.META_PARAMS.WEIGHT_PREDICTOR = CN()
_CC.META_PARAMS.WEIGHT_PREDICTOR.FEAT_SIZE = 1024
_CC.META_PARAMS.WEIGHT_PREDICTOR.BOX_DIM = 4