_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_5shot_combine/model_reset_combine.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 80
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  # PRETRAINED_BASE_MODEL: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_final.pth"
DATASETS:
  TRAIN: ('coco_trainval_all_5shot',)
  TEST: ('coco_test_all',)
SOLVER:
  IMS_PER_BATCH: 16
  # IMS_PER_BATCH_FEAT_EXTRACT: 10
  BASE_LR: 0.001
  STEPS: (72000,)
  MAX_ITER: 80000
  # CHECKPOINT_PERIOD: 4000
  CHECKPOINT_PERIOD: 50
  WARMUP_ITERS: 10
# DATALOADER:
#   ASPECT_RATIO_GROUPING: False
CG_PARAMS:
  NUM_NEWTON_ITER: 400
  NUM_CG_ITER: 2
OUTPUT_DIR: "checkpoints_temp/CG_L2/coco/cg2_shot5_iter400/faster_rcnn/faster_rcnn_R_101_FPN_ft_all_5shot"