_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  PRETRAINED_BASE_MODEL: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_final.pth"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_all1_1shot',)
  TEST: ('voc_2007_test_all1',)
SOLVER:
  IMS_PER_BATCH: 16
  IMS_PER_BATCH_FEAT_EXTRACT: 10
  BASE_LR: 0.001
  STEPS: (3000,)
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 500
  # CHECKPOINT_PERIOD: 25
  WARMUP_ITERS: 0
DATALOADER:
  ASPECT_RATIO_GROUPING: False
CG_PARAMS:
  # NUM_NEWTON_ITER: 4000
  NUM_NEWTON_ITER: 200
  NUM_CG_ITER: 2
  # DEBUG: True
  # ANALYZE_CONVERGENCE: True
  # PLOTTING: True
  LOSS_REG: 5e-3
# TODO change the output_dir later on specifically for CG, with run_experiments.py
OUTPUT_DIR: "checkpoints_temp/CG_L2_test/voc/cg_iter2_200_reg5e-3/faster_rcnn/faster_rcnn_R_101_FPN_ft_normalized_all1_1shot_randnovel"
# OUTPUT_DIR: "checkpoints_temp/SGD_L2_modified/voc/exp_3_reg/faster_rcnn/faster_rcnn_R_101_FPN_ft_normalized_all1_1shot_randnovel"
