_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_1shot_combine/model_reset_combine.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 60
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  PRETRAINED_BASE_MODEL: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_final.pth"
DATASETS:
  TRAIN: ('coco_trainval_all_1shot',)
  TEST: ('coco_test_all',)
SOLVER:
  IMS_PER_BATCH: 16
  IMS_PER_BATCH_FEAT_EXTRACT: 5
  BASE_LR: 0.001
  STEPS: (14400,)
  MAX_ITER: 16000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 10
DATALOADER:
  ASPECT_RATIO_GROUPING: False
CG_PARAMS:
  NUM_NEWTON_ITER_WARMUP: 0
  NUM_NEWTON_ITER: 5
  # NUM_NEWTON_ITER: 0
  NUM_CG_ITER: 2
  AUGMENTATION: False
META_PARAMS:
  MODEL_WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_final.pth"
  REGULARIZATION_TYPE: 'feature wise'
  INIT_LOSS_REG: 1.0
  NUM_ITER: 1000
  TASKS_PER_BATCH: 1
  SUPPORT_SET_SHOTS: 1
  QUERY_SET_SHOTS: 1
  BASE_CATEGORIES_PATH: "datasets/cocosplit/datasplit/coco_base_categories.pt"
  TRAINING_DATA_PATH: "datasets/cocosplit/datasplit/trainvalno5k.json"
  OUTER_OPTIM:
    BASE_LR: 0.01
    MOMENTUM: 0.9
    NESTEROV: False
    WEIGHT_DECAY: 0.0001
OUTPUT_DIR: "checkpoints_temp/CG_L2_meta_weight_retrained/coco_meta_weight_regvec_std1e-1_iter1000_lr1e-2/faster_rcnn_R_101_FPN_ft_all_1shot"
# OUTPUT_DIR: "checkpoints_temp/CG_L2_meta_test/coco_meta_reg1_iter500_nowarm/faster_rcnn_R_101_FPN_ft_all_1shot"

# OUTPUT_DIR: "checkpoints_temp/SGD_L2_modified/coco/exp_2_reg_fullFeat/faster_rcnn/faster_rcnn_R_101_FPN_ft_all_1shot"