CG_PARAMS:
  HESSIAN_REG_FACTOR: 1.0
  INIT_HESSIAN_REG: 0.5
  NUM_CG_ITER: 2
  NUM_NEWTON_ITER: 1
DATASETS:
  TEST: !!python/tuple
  - coco_test_all
  TRAIN: !!python/tuple
  - coco_trainval_all_2shot
MODEL:
  BACKBONE:
    FREEZE: true
  MASK_ON: false
  PROPOSAL_GENERATOR:
    FREEZE: true
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    FREEZE_FEAT: true
    NAME: TwoStageROIHeads
    NUM_CLASSES: 80
    NUM_CLASSES_BASE: 60
    NUM_CLASSES_NOVEL: 20
    OUTPUT_LAYER: FastRCNNOutputLayers
  WEIGHTS: checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_all/model_reset_surgery_ts.pth
OUTPUT_DIR: ./checkpoints/thesis/checkpoints_HDA_SCG/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_fc_all_2shot
SOLVER:
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 8
  MAX_ITER: 200
  NUM_BATCHES_PER_SET: 2
_BASE_: ../../Base-RCNN-FPN.yaml
