_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  # WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_10shot_combine/model_reset_combine.pth"
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_all/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 80
    OUTPUT_LAYER: "CosineSimOutputLayers"
    # OUTPUT_LAYER: "FastRCNNOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_all_10shot',)
  TEST: ('coco_test_all',)
SOLVER:
  MAX_ITER: 100
  CHECKPOINT_PERIOD: 20
  IMS_PER_BATCH: 10
  NUM_BATCHES_PER_SET: 40
  WARMUP_ITERS: 0
# add
# DATALOADER:
#   ASPECT_RATIO_GROUPING: False
# add
CG_PARAMS:
  NUM_NEWTON_ITER: 1
  NUM_CG_ITER: 2
  # INIT_HESSIAN_REG: 0.4
  # HESSIAN_REG_FACTOR: 0.9
OUTPUT_DIR: "checkpoints_temp/COCO_TFA_SCG/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_all_10shot_SCG_test"
